# https://starship.rs/config/

[swift]
symbol = "ğŸ™ "

### Battery
[battery]
discharging_symbol = "ğŸ’€ "

[[battery.display]]
threshold = 20
style = "bold red"

### Git
[git_branch]
symbol = "ğŸ¦– "

[git_status]
up_to_date = "âœ…"
stashed = "ğŸ“¦"
modified = "ğŸ“"
conflicted = "ğŸš§"
renamed = "ğŸ¹"
deleted = "ğŸ—‘"
untracked = "ğŸ¤·"
ahead = "ğŸğŸ’¨${count}"
behind = "ğŸ˜°${count}"
staged = '[++\($count\)](green)'
diverged = "ğŸ˜µâ‡¡${ahead_count}â‡£${behind_count}"
